export const captureException = (e: any) => {
  return
}